language: scala
sudo: false
dist: trusty

jdk:
  - openjdk8

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" publishLocal test 

matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    scala: 2.10.6

  - env: SBT_VERSION="1.0.1"
    scala: 2.12.2
